#!/usr/bin/env bash
# Run the p_n-range (low-p_n) study: every XML below xml/lowpn_study/<family>/<variant>/,
# generated by python/scripts/make_lowpn_study_xmls.py. Same options and environment as
# xml/binning_study/run_all.sh; results go to OUTPUT_ROOT/lowpn_study_fit_results/<family>/<variant>/<fit>/.
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STUDY_DIR="${script_dir}" STUDY_NAME="lowpn_study" exec "${script_dir}/../binning_study/run_all.sh" "$@"
