#!/usr/bin/env bash
set -euo pipefail

# Run the injection (bias) study listed in runs.txt. The XMLs and runs.txt are
# generated by python/scripts/make_injection_study_xmls.py from knobs.json (itself
# written by python/notebooks/19_modeling_knob_screen.ipynb); regenerate them there
# rather than editing them here.

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
output_root="${OUTPUT_ROOT:-/nevis/hopper/data/epelaez/axial_mass}"
study_output="${output_root}/injection_study_fit_results"
profit_bin="${PROFIT_BIN:-/nevis/riverside/share/epelaez/PROfit/build/bin/PROfit}"
nthreads="${NTHREADS:-8}"
max_jobs="${JOBS:-4}"
stages="${STAGES:-profile}"
baseline_stages="${BASELINE_STAGES:-profile}"
dry_run="${DRY_RUN:-0}"
manifest="${script_dir}/runs.txt"

usage() {
    cat <<'USAGE'
Usage: ./run_all.sh [options]

Run every fit in runs.txt. Each XML (one base fit with one knob promoted to a
spline) is processed once in its own output directory,
OUTPUT_ROOT/injection_study_fit_results/<variant>/<fit>/<knob>/, and its
injections then reuse the cached binaries there:

    PROfit --xml <knob>.xml --tag <fit> --output inj<sigma> \
           --inject-systs <knob> <sigma> --fix <knob> profile

The baseline XML (the base fit unchanged) runs without injection, with
--output baseline. Different XMLs run in parallel, JOBS at a time.

Options:
  --fit NAME       Run only this base fit (repeatable)
  --knob NAME      Run only this knob; "baseline" selects the baselines (repeatable)
  -h, --help       Show this help

Environment:
  FIT="lqcd_k6"               Same as repeated --fit
  KNOB="RPA_CCQE_UBGenie"     Same as repeated --knob
  JOBS=4                      XMLs processed/fitted at the same time
  NTHREADS=8                  PROfit threads per job
  STAGES=profile              Stages for the injected fits. profile scans the axial parameters and
                              adopts a lower minimum than the global fit found (needed: the
                              global stage alone got stuck in a local minimum, 2026-09-30)
  BASELINE_STAGES=profile     Stages for the baselines (profile gives the F_A uncertainties)
  OUTPUT_ROOT, PROFIT_BIN, DRY_RUN behave as in xml/run_all.sh.
USAGE
}

requested_fits=()
[[ -n "${FIT:-}" ]] && read -r -a requested_fits <<< "${FIT}"
requested_knobs=()
[[ -n "${KNOB:-}" ]] && read -r -a requested_knobs <<< "${KNOB}"

while (($#)); do
    case "$1" in
        --fit|--knob)
            if (($# < 2)); then
                echo "$1 requires a name" >&2
                exit 2
            fi
            if [[ "$1" == "--fit" ]]; then requested_fits+=("$2"); else requested_knobs+=("$2"); fi
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

if [[ ! -f "${manifest}" ]]; then
    echo "No ${manifest}; generate it with python/scripts/make_injection_study_xmls.py." >&2
    exit 1
fi
if [[ ! -x "${profit_bin}" && "${dry_run}" != "1" ]]; then
    echo "PROfit executable is not available: ${profit_bin}" >&2
    exit 1
fi

contains() {
    local needle="$1"; shift
    local item
    for item in "$@"; do [[ "${item}" == "${needle}" ]] && return 0; done
    return 1
}

# Group the manifest by XML: "<variant> <fit> <stem>" -> its "<knob> <sigma>" lines, in file order.
declare -A group_runs=()
groups=()
while read -r variant fit stem knob sigma; do
    [[ -z "${variant}" || "${variant}" == \#* ]] && continue
    if ((${#requested_fits[@]})) && ! contains "${fit}" "${requested_fits[@]}"; then continue; fi
    if ((${#requested_knobs[@]})) && ! contains "${stem}" "${requested_knobs[@]}"; then continue; fi
    key="${variant} ${fit} ${stem}"
    if [[ -z "${group_runs[${key}]:-}" ]]; then
        groups+=("${key}")
        group_runs[${key}]=""
    fi
    group_runs[${key}]+="${knob} ${sigma}"$'\n'
done < "${manifest}"

if ((${#groups[@]} == 0)); then
    echo "Nothing selected from ${manifest}." >&2
    exit 2
fi

missing_inputs=()
while IFS= read -r input_file; do
    [[ -f "${input_file}" ]] || missing_inputs+=("${input_file}")
done < <(
    for key in "${groups[@]}"; do
        read -r variant fit stem <<< "${key}"
        grep -ho 'filename="[^"]*"' "${script_dir}/${variant}/${fit}/${stem}.xml"
    done | cut -d'"' -f2 | sort -u
)
if ((${#missing_inputs[@]})); then
    echo "The following configured inputs do not exist yet:" >&2
    printf '  %s\n' "${missing_inputs[@]}" >&2
    [[ "${dry_run}" == "1" ]] || exit 1
fi

run_profit() {
    # run_profit <dir> <xml> <tag> <output> <log> <stage> [extra global args...]
    local dir="$1" xml="$2" tag="$3" output="$4" log="$5" stage="$6"
    shift 6
    local cmd=("${profit_bin}" --xml "${xml}" --tag "${tag}" --output "${output}"
               --nthread "${nthreads}" --log "${log}" "$@" "${stage}")
    if [[ "${dry_run}" == "1" ]]; then
        printf '(cd %q &&' "${dir}"
        printf ' %q' "${cmd[@]}"
        printf ')\n'
        return 0
    fi
    # PROfit logs to --log; ROOT chatter and any crash output go to <log>.out
    (cd "${dir}" && "${cmd[@]}" > "${log%.log}.out" 2>&1)
}

run_group() {
    # All fits of one XML, serially, so the binaries processed by the first are reused.
    local key="$1"
    local variant fit stem knob sigma stage
    read -r variant fit stem <<< "${key}"
    local xml="${script_dir}/${variant}/${fit}/${stem}.xml"
    local dir="${study_output}/${variant}/${fit}/${stem}"
    [[ "${dry_run}" == "1" ]] || mkdir -p "${dir}"
    while read -r knob sigma; do
        [[ -z "${knob}" ]] && continue
        if [[ "${knob}" == "-" ]]; then
            for stage in ${baseline_stages}; do
                run_profit "${dir}" "${xml}" "${fit}" baseline "${stage}_baseline.log" "${stage}" || return 1
            done
        else
            for stage in ${stages}; do
                run_profit "${dir}" "${xml}" "${fit}" "inj${sigma}" "${stage}_inj${sigma}.log" "${stage}" \
                    --inject-systs "${knob}" "${sigma}" --fix "${knob}" || return 1
            done
        fi
    done <<< "${group_runs[${key}]}"
    [[ "${dry_run}" == "1" ]] || echo "done   ${variant}/${fit}/${stem}"
    return 0
}

echo "==> ${#groups[@]} XMLs, ${max_jobs} at a time, ${nthreads} threads each -> ${study_output}"
[[ "${dry_run}" == "1" ]] && max_jobs=1

# Each group records its own failure: wait -n reaps jobs, so their statuses cannot be collected later.
failures="$(mktemp)"
trap 'rm -f "${failures}"' EXIT
for key in "${groups[@]}"; do
    while (($(jobs -rp | wc -l) >= max_jobs)); do
        wait -n || true
    done
    [[ "${dry_run}" == "1" ]] || echo "start  ${key// //}"
    { run_group "${key}" || echo "${key// //}" >> "${failures}"; } &
done
wait
mapfile -t failed < "${failures}"

if ((${#failed[@]})); then
    echo "Failed (see the logs in their output directories):" >&2
    printf '  %s\n' "${failed[@]}" >&2
    exit 1
fi
