#!/usr/bin/env python3
"""Generate the injection-study XMLs from the binning-study base fits.

The injection (bias) study injects one modeling knob X into the Asimov fake data,
holds X at its CV in the fit (``--fix``), floats the axial form factor and
measures how far it moves. PROfit can only inject and fix ``type="spline"``
systematics, so for every (base fit, knob) this writes the base fit with only
that knob's ``<systematic>`` turned from ``spline_to_covariance`` into
``spline``. Every other modeling knob is a ``spline_to_covariance``: the ones
the base fit floats as splines (``RPA_CCQE``, ``NormCCMEC`` in the M_A fits)
are turned into covariance systematics, in the baseline too, so the only free
parameters are the axial ones (``AXIAL``). Everything else keeps its production
treatment.

The knobs, their shifts and the base fits come from
``xml/injection_study/knobs.json``, written by
``python/notebooks/19_modeling_knob_screen.ipynb``. The base fits are
``xml/binning_study/asimov/<variant>/<fit>.xml``. Outputs:

* ``xml/injection_study/<variant>/<fit>/<knob>.xml``, one per injected knob;
* ``xml/injection_study/<variant>/<fit>/baseline.xml``, the base fit with every
  modeling knob in the covariance, as the uninjected reference;
* ``xml/injection_study/runs.txt``, one line per fit for
  ``xml/injection_study/run_all.sh``: ``<variant> <fit> <xml stem> <knob> <sigma>``
  (knob and sigma are ``-`` for the baseline).

Usage:
    python/scripts/make_injection_study_xmls.py

It always rewrites every XML and the whole manifest (it takes a second);
select fits and knobs when running, with run_all.sh's --fit and --knob.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STUDY_DIR = ROOT / "xml" / "injection_study"
KNOBS_JSON = STUDY_DIR / "knobs.json"
BINNING_STUDY = ROOT / "xml" / "binning_study" / "asimov"

# Modeling knobs (demoted to covariance unless under test) and the axial splines that stay free.
MODELING = re.compile(r"\w+_UBGenie|\w+_SCC")
AXIAL = {"MaCCQE_UBGenie", "AxFFCCQEshape_UBGenie"}

SYSTEMATIC = re.compile(r"<systematic\s[^>]*>\s*([^<\s]+)\s*</systematic>")
COMMENT = re.compile(r"<!--.*?-->", re.S)


def comment_spans(text: str) -> list[tuple[int, int]]:
    return [m.span() for m in COMMENT.finditer(text)]


def find_systematic(text: str, knob: str) -> re.Match:
    """The single uncommented <systematic> element for ``knob``."""
    spans = comment_spans(text)
    hits = [
        m for m in SYSTEMATIC.finditer(text)
        if m.group(1) == knob and not any(a <= m.start() < b for a, b in spans)
    ]
    if len(hits) != 1:
        raise ValueError(f"{knob}: expected one uncommented <systematic>, found {len(hits)}")
    return hits[0]


def uncommented_systematics(text: str) -> list[re.Match]:
    spans = comment_spans(text)
    return [m for m in SYSTEMATIC.finditer(text) if not any(a <= m.start() < b for a, b in spans)]


def set_type(text: str, match: re.Match, kind: str) -> str:
    element = re.sub(r'\btype="[^"]*"', f'type="{kind}"', match.group(0), count=1)
    return text[: match.start()] + element + text[match.end():]


def configure(text: str, knob: str | None) -> tuple[str, list[str]]:
    """``knob`` as a spline and every other floated modeling knob in the covariance.

    Returns the new text and the knobs that were demoted from ``spline``.
    """
    demoted = []
    # Edit from the end so earlier match offsets stay valid.
    for m in reversed(uncommented_systematics(text)):
        name = m.group(1)
        kind = re.search(r'\btype="([^"]*)"', m.group(0)).group(1)
        if name == knob:
            if kind not in ("spline", "spline_to_covariance"):
                raise ValueError(f"{knob}: type {kind!r} cannot be injected")
            text = set_type(text, m, "spline")
        elif kind == "spline" and MODELING.fullmatch(name) and name not in AXIAL:
            text = set_type(text, m, "spline_to_covariance")
            demoted.append(name)
    if knob is not None:
        find_systematic(text, knob)   # exactly one uncommented element
    return text, sorted(demoted)


def with_header(text: str, lines: list[str]) -> str:
    """Insert a generated-by comment after the XML declaration, replacing the base's one."""
    text = re.sub(r"<!-- Generated by .*?-->\n", "", text, count=1, flags=re.S)
    decl, rest = text.split("\n", 1) if text.startswith("<?xml") else ("", text)
    comment = "<!-- " + "\n     ".join(lines) + " -->\n"
    return (decl + "\n\n" if decl else "") + comment + rest.lstrip("\n")


def sigma_tag(sigma: float) -> str:
    return f"{sigma:g}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.parse_args()

    config = json.loads(KNOBS_JSON.read_text())
    variant = config["_meta"]["variant"]
    fits = config["_meta"]["base_fits"]
    knobs = config["knobs"]

    runs = []
    for fit in fits:
        base_path = BINNING_STUDY / variant / f"{fit}.xml"
        base = base_path.read_text()
        out_dir = STUDY_DIR / variant / fit
        out_dir.mkdir(parents=True, exist_ok=True)
        source = base_path.relative_to(ROOT)

        text, demoted = configure(base, None)
        moved = f" ({', '.join(demoted)} spline -> spline_to_covariance)" if demoted else ""
        (out_dir / "baseline.xml").write_text(with_header(text, [
            f"Generated by python/scripts/make_injection_study_xmls.py from {source}.",
            f"Injection-study baseline: every modeling knob in the covariance{moved}.",
            "Do not edit by hand.",
        ]))
        runs.append((variant, fit, "baseline", "-", "-"))

        for knob, spec in knobs.items():
            text, demoted = configure(base, knob)
            moved = f"; {', '.join(demoted)} spline -> spline_to_covariance" if demoted else ""
            (out_dir / f"{knob}.xml").write_text(with_header(text, [
                f"Generated by python/scripts/make_injection_study_xmls.py from {source}.",
                f"Injection study: {knob} as a spline{moved}; all else unchanged.",
                f"Run with --inject-systs {knob} <sigma> --fix {knob}. Do not edit by hand.",
            ]))
            runs.extend((variant, fit, knob, knob, sigma_tag(s)) for s in spec["sigmas"])
        print(f"{variant}/{fit}: baseline + {len(knobs)} knob XMLs")

    manifest = STUDY_DIR / "runs.txt"
    manifest.write_text(
        "# variant fit xml_stem knob sigma  (written by python/scripts/make_injection_study_xmls.py)\n"
        + "".join(" ".join(r) + "\n" for r in runs)
    )
    print(f"{manifest.relative_to(ROOT)}: {len(runs)} fits")
    return 0


if __name__ == "__main__":
    sys.exit(main())
